site_name: Plutus Community Docs
repo_url: https://github.com/plutus-community/docs/
theme: 
  name: windmill # cleaner for nested content and supporting more than 2 levels of depth
  #name: rtd-dropdown
  #name: readthedocs
  collapse_navigation: true
  sticky_navigation: false
  navigation_depth: 4
  includehidden: true
  titles_only: false
  features:
    - content.code.annotate
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list # For using e.g. [](){:target="_blank"}:

# Navigation is defined in external yml file, which is placed
# in docs/ directory for triggering reload when changed:
INHERIT: docs/mkdocs.navigation.yml
